export const vector: string[][] = [
    // ["need", "people-circle", "first"],
    // ["list", "collection", "fifth"],
    // ["have", "home", "sixth"],
    
    // ["padaria", "people-circle", "first"],
    // ["mercearia", "calendar3", "second"],
    // ["bebidas", "toggles2", "second"],
    // ["frios", "table", "third"],
    // ["limpeza", "chat-quote-fill", "fourth"],
    // ["higiene", "collection", "fifth"],
    // ["frutas", "home", "sixth"],
    // ["legumes", "speedometer2", "sixth"],
    // ["pet", "cpu-fill", "sixth"],

    ["user", "people-circle", "first"],
    ["role", "toggles2", "third"],
    ["leafletMap", "calendar3", "second"],
    ["blind", "table", "fourth"],
    // ["food_category", "table", "fourth"],
    // ["military", "chat-quote-fill", "fifth"],
    // ["composite_unit", "collection", "sixth"],
    // ["weather", "table", "sixth"],
    // ["weatherOffShore", "home", "sixth"],
    // ["commission", "collection", "sixth"],
    ["chart", "chevron-right", "sixth"],
    ["chart-area", "tools", "sixth"],
    ["maritime-area", "gear-fill", "sixth"],
    ["gauge-station", "chat-quote-fill", "sixth"],
    ["state", "collection", "sixth"],
    ["city", "grid", "sixth"],
    ["country", "speedometer2", "sixth"],
    // ["equipment", "people-circle", "sixth"],
    // ["harbor", "grid", "sixth"],
    // ["institution", "collection", "sixth"],
    // ["manufacturer", "collection", "sixth"],
    // ["observer", "collection", "sixth"],
    // ["om", "collection", "sixth"],
    // ["platform", "calendar3", "sixth"],
    // ["platform_category", "chat-quote-fill", "sixth"],
    // ["researcher", "collection", "sixth"],
    // ["station", "chm", "sixth"],
    // ["stationCategory", "gear-fill", "sixth"],
    // ["stationOffShore", "speedometer", "sixth"],
    // ["stationOnShore", "toggles2", "sixth"],
    // ["surveying", "collection", "sixth"],
    // ["user", "grid", "sixth"],
    // ["tooltip role", "chevron-right", "sixth"]
]